spring:
  application:
    name: config-server
  boot:
    admin:
      client:
        url: http://localhost:8081
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spider-pug/configs
          skipSslValidation: true
          clone-on-start: true

server:
  port: 8888


management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false